fpm7:
    build: ./php7
    volumes:
          - ../html/:/var/www/html
          - ./php7/local.ini:/usr/local/etc/php/conf.d/local.ini
nginx:
    image: 'hub.c.163.com/library/nginx:1.11'
    ports:
      - "81:80"
      - "91:91"
      - "92:92"
    volumes:
        - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - fpm7
    links:
      - "fpm7"